// SPDX-License-Identifier: MIT
pragma solidity 0.8.22;

import { BaseDecoderAndSanitizer } from "src/base/DecodersAndSanitizers/BaseDecoderAndSanitizer.sol";

/**
 * @title TradeVuVaultDecoderAndSanitizer
 * @notice Strategy decoder for the Clearpool × TradeVu borrower-draw vault.
 *
 *         Two on-chain strategy actions exist, and the decoder exposes exactly the sanitizers they need:
 *
 *           1. BORROW — the borrower draws funds out of the vault:
 *                - transfer(address to, uint256): pins the recipient, so the merkle leaf binds TradeVu
 *
 *           2. FEE CLAIM — Clearpool sweeps accrued management fees to the accountant's payoutAddress:
 *                - approve(address spender, uint256): inherited from BaseDecoderAndSanitizer (pins spender)
 *                - claimFees(address feeAsset): pins the fee asset
 *              `AccountantWithRateProviders.claimFees` is `msg.sender == address(vault)`-gated and performs
 *              `feeAsset.safeTransferFrom(vault, payoutAddress, owed)`, so the vault must approve the
 *              accountant first — hence both leaves. The destination is NOT a decoder argument: it is the
 *              accountant's own `payoutAddress`, which only the accountant's owner can change.
 *
 *         Every other selector hits BaseDecoderAndSanitizer's fallback revert. No unpinned-recipient gaps.
 *         Repayments are direct transfers TO the vault and require no leaf at all.
 *
 *         The `claimFees(address)` leaf shape matches the one generated by
 *         `resources/BaseMerkleRootGenerator.sol` and already live in `leafs/LiquidUsdStrategistLeafs.json`
 *         (target = accountant, selector 0x15a0ea6a, one pinned argument = the fee asset).
 */
contract TradeVuVaultDecoderAndSanitizer is BaseDecoderAndSanitizer {
    constructor(address _boringVault) BaseDecoderAndSanitizer(_boringVault) { }

    // @desc ERC20 transfer — recipient is pinned into the merkle leaf
    // @tag to:address
    function transfer(address to, uint256) external pure returns (bytes memory addressesFound) {
        addressesFound = abi.encodePacked(to);
    }

    // @desc Claim accrued management fees to the accountant's payoutAddress — fee asset is pinned
    // @tag feeAsset:address
    function claimFees(address feeAsset) external pure returns (bytes memory addressesFound) {
        addressesFound = abi.encodePacked(feeAsset);
    }
}
